databases:
  - name: suppliersdb
    plan: free
    databaseName: suppliersdb
    user: simppa

services:
  - type: web
    plan: free
    name: suppliers
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: suppliersdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4